https://en.wikipedia.org/wiki/Quantum_computing

I want to change 


John Preskill has introduced the term quantum supremacy to refer to the hypothetical speedup advantage that a quantum computer would have over a classical computer in a certain field.[39] Google announced in 2017 that it expected to achieve quantum supremacy by the end of the year though that did not happen. IBM said in 2018 that the best classical computers will be beaten on some practical task within about five years and views the quantum supremacy test only as a potential future benchmark.[40] Although skeptics like Gil Kalai doubt that quantum supremacy will ever be achieved,[41][42] in October 2019, a Sycamore processor created in conjunction with Google AI Quantum was reported to have achieved quantum supremacy,[43] with calculations more than 3,000,000 times as fast as those of Summit, generally considered the world's fastest computer.[44] In December 2020, a group at USTC implemented a type of Boson sampling on 76 photons with a photonic quantum computer Jiuzhang to demonstrate quantum supremacy.[45][46][47] The authors claim that a classical contemporary supercomputer would require a computational time of 600 million years to generate the number of samples their quantum processor can generate in 20 seconds.[48] Bill Unruh doubted the practicality of quantum computers in a paper published back in 1994.[49] Paul Davies argued that a 400-qubit computer would even come into conflict with the cosmological information bound implied by the holographic principle.[50] 


to 



John Preskill has introduced the term quantum supremacy to refer to the hypothetical speedup advantage that a quantum computer would have over a classical computer in a certain field.[39] Google announced in 2017 that it expected to achieve quantum supremacy by the end of the year though that did not happen. IBM said in 2018 that the best classical computers will be beaten on some practical task within about five years and views the quantum supremacy test only as a potential future benchmark.[40] Although skeptics like Gil Kalai doubt that quantum supremacy will ever be achieved,[41][42] in October 2019, a Sycamore processor created in conjunction with Google AI Quantum was reported to have achieved quantum supremacy,[43] with calculations more than 3,000,000 times as fast as those of Summit, generally considered the world's fastest computer.[44] In December 2020, a group at USTC implemented a type of Boson sampling on 76 photons with a photonic quantum computer Jiuzhang to demonstrate quantum supremacy.[45][46][47] The authors claim that a classical contemporary supercomputer would require a computational time of 600 million years to generate the number of samples their quantum processor can generate in 20 seconds.[48] Bill Unruh doubted the practicality of quantum computers in a paper published back in 1994.[49] Paul Davies argued that a 408-qubit computer would even come into conflict with the cosmological information bound implied by the holographic principle.[50] 
